
-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- PROFILES TABLE
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique not null,
  display_name text,
  bio text,
  avatar_url text,
  theme text default 'default',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint username_length check (char_length(username) >= 3)
);

-- LINKS TABLE
create table public.links (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  url text not null,
  position integer default 0,
  is_active boolean default true,
  clicks integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CLICKS TABLE (Analytics)
create table public.clicks (
  id bigint generated by default as identity primary key,
  link_id uuid references public.links(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  referrer text,
  country text,
  city text,
  user_agent text
);

-- RLS POLICIES

-- Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Links
alter table public.links enable row level security;

create policy "Public links are viewable by everyone."
  on public.links for select
  using ( true );

create policy "Users can insert their own links."
  on public.links for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own links."
  on public.links for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own links."
  on public.links for delete
  using ( auth.uid() = user_id );

-- Clicks
alter table public.clicks enable row level security;

create policy "Users can view clicks for their links."
  on public.clicks for select
  using (
    exists (
      select 1 from public.links
      where public.links.id = public.clicks.link_id
      and public.links.user_id = auth.uid()
    )
  );

create policy "Anyone can insert clicks."
  on public.clicks for insert
  with check ( true );

-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data ->> 'username', -- Assuming username is passed in metadata
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
